package com.finzen.app.ui.theme

import androidx.compose.ui.graphics.Color

val Emerald = Color(0xFF820AD1)
val EmeraldBright = Color(0xFFD2B3FF)
val EmeraldDeep = Color(0xFF5B0A92)
val EmeraldInk = Color(0xFF1E0833)

val LightPrimary = Emerald
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFEBD9FB)
val LightOnPrimaryContainer = Color(0xFF2E0A4F)
val LightSecondary = Color(0xFF3B8ED0)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0EBFF)
val LightOnSecondaryContainer = Color(0xFF08344D)
val LightTertiary = Color(0xFF7C5CFC)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFE5DBFF)
val LightOnTertiaryContainer = Color(0xFF2A1A66)
val LightBackground = Color(0xFFF5F7F9)
val LightOnBackground = Color(0xFF131A20)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF131A20)
val LightSurfaceVariant = Color(0xFFEAF0F2)
val LightOnSurfaceVariant = Color(0xFF51606B)
val LightOutline = Color(0xFFB9C4CC)
val LightOutlineVariant = Color(0xFFDDE4E9)
val LightError = Color(0xFFE5484D)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFE3E3)
val LightOnErrorContainer = Color(0xFF5A1115)
val LightInverseSurface = Color(0xFF1E2A32)
val LightInverseOnSurface = Color(0xFFEFF4F6)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F4F6)
val LightSurfaceContainer = Color(0xFFECF1F3)
val LightSurfaceContainerHigh = Color(0xFFE5ECEF)
val LightSurfaceContainerHighest = Color(0xFFDFE7EA)

val DarkPrimary = EmeraldBright
val DarkOnPrimary = Color(0xFF381E72)
val DarkPrimaryContainer = Color(0xFF5B0A92)
val DarkOnPrimaryContainer = Color(0xFFEBD9FF)
val DarkSecondary = Color(0xFF74C0FC)
val DarkOnSecondary = Color(0xFF08344D)
val DarkSecondaryContainer = Color(0xFF0B4A6B)
val DarkOnSecondaryContainer = Color(0xFFC5E5FF)
val DarkTertiary = Color(0xFFB197FC)
val DarkOnTertiary = Color(0xFF2A1A66)
val DarkTertiaryContainer = Color(0xFF4A3A8C)
val DarkOnTertiaryContainer = Color(0xFFE5DBFF)

val DarkBackground = Color(0xFF161519)
val DarkOnBackground = Color(0xFFE8E6EF)
val DarkSurface = Color(0xFF1D1C24)
val DarkOnSurface = Color(0xFFE8E6EF)
val DarkSurfaceVariant = Color(0xFF26242E)
val DarkOnSurfaceVariant = Color(0xFFAAA6B7)
val DarkOutline = Color(0xFF3A3743)
val DarkOutlineVariant = Color(0xFF26242E)
val DarkError = Color(0xFFFF8A8A)
val DarkOnError = Color(0xFF5A1115)
val DarkErrorContainer = Color(0xFF7A2429)
val DarkOnErrorContainer = Color(0xFFFFD9D9)
val DarkInverseSurface = Color(0xFFE8E6EF)
val DarkInverseOnSurface = Color(0xFF1F1E27)
val DarkSurfaceContainerLowest = Color(0xFF131217)
val DarkSurfaceContainerLow = Color(0xFF1B1A21)
val DarkSurfaceContainer = Color(0xFF201E27)
val DarkSurfaceContainerHigh = Color(0xFF262430)
val DarkSurfaceContainerHighest = Color(0xFF2D2B37)

fun colorFromHex(hex: String): Color =
    runCatching { Color(android.graphics.Color.parseColor(hex)) }
        .getOrDefault(Color(0xFF868E96))
